In [1]:
%pylab
import dataProc_cal as dp
import pandas as pd
import os
import scipy.optimize as op
from scipy.interpolate import interp1d
import scipy.signal as signal
import findEField as fef
import conf

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [30]:
reload(dp)

<module 'dataProc_cal' from 'dataProc_cal.py'>

In [95]:
x = dp.readArray("/run/media/brant/5734-6A19/0000")
print x[1018:1024]
print x[1024:1030]

[2441 2176 2452 2436 5476 2924]
[8868 2924 2163 2444 2423 2159]


In [92]:
figure()
a = dp.readData("../docs/noise/testdata/CErL")
specgram(a[1]['adc'],NFFT=1024,Fs=1/(a[1]['t'][2]-a[1]['t'][1]),interpolation="none")
colorbar()
#plot(a[0]['t'],a[0]['adc'])
#plot(a[1]['t'],a[1]['adc'])
#plot(a[2]['t'],a[2]['adc'])

<matplotlib.colorbar.Colorbar instance at 0x7f3d6c813cf8>

In [86]:
figure()

In [99]:
#a = dp.readData("../docs/noise/testdata/CErL")
plot(a[0]['t'],a[0]['adc'])
plot(a[1]['t'],a[1]['adc'])
plot(a[2]['t'],a[2]['adc'])
#xlim(0,100)
#ylim(0,500)

In [102]:
a = dp.splitData(dp.readArray("/run/media/brant/5734-6A19/0000"))

In [103]:
a

{'d0': array([2190, 2185, 2179, ..., 1939, 1939, 1935], dtype=uint16),
 'd1': array([2508, 2503, 2497, ..., 2390, 2391, 2391], dtype=uint16),
 'd2': array([2476, 2471, 2464, ..., 2499, 2503, 2511], dtype=uint16),
 'end': array([ 191632740,  194103412,  196574084,  199044756,  201517252,
         203987924,  230016516,  240743572,  243216068,  245686740,
         248159236,  250629908,  253102404,  255573076,  258045572,
         260516244,  262988740,  265459412,  267931908,  270402580,
         272875076,  275345748,  277818244,  280288916,  282761412,
         285232084,  287704580,  290175252,  292647748,  295118420,
         297590916,  300061588,  302534084,  305004756,  307477252,
         309947924,  312420420,  314891092,  317363588,  319834260,
         322306756,  324777428,  327249924,  329720596,  332193092,
         334663764,  337136260,  339606932,  342079428,  344550100,
         347022596,  349493268,  351965764,  354436436,  356908932,
         359379604,  361852100, 

In [120]:
a['start'][54:74]

array([354441652, 356912324, 359384820, 361855492, 364327988, 366798660,
       369271156, 371741828, 374214324, 189165460, 376684996, 379157492,
       381628164, 384100660, 386571332, 389043828, 391514500, 393986996,
       396457668, 398930164], dtype=uint32)

In [121]:
b = dp.readArray("/run/media/brant/5734-6A19/0000")

In [128]:
nn = 55
b[nn*1024-5:nn*1024]

array([ 1951,  2390,  2363, 65412,  5445], dtype=uint16)

In [129]:
b[nn*1024:nn*1024+5]

array([3268, 5446, 1951, 2392, 2369], dtype=uint16)

In [131]:
2**32/80000000.0

53.6870912