In [1]:
%pylab
import sys
sys.path.append("/home/brant/caerenet/git/dataProc")

import dataProc_cal as dp

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [29]:
def plotTestData0(fn,tmin=15,twindow=(30,30.2)):
    a = dp.readData(fn)
    a0 = a[0].loc[a[0]['t']>tmin]
    a1 = a[1].loc[a[1]['t']>tmin]
    a2 = a[2].loc[a[2]['t']>tmin]
    #plot(a0['t'],a0['adc'])
    plot(a1['t'],a1['adc'],label="ch1")
    plot(a2['t'],a2['adc'],label="ch2")
    legend()
    xlim(twindow[0],twindow[1])

In [58]:
def plotTestData(fn,c='blue',tmin=15,twindow=(30,30.2)):
    a = dp.readData(fn)
    a0 = a[0].loc[a[0]['t']>tmin]
    a1 = a[1].loc[a[1]['t']>tmin]
    a2 = a[2].loc[a[2]['t']>tmin]
    subplot(311)
    plot(a0['t'],a0['adc'],color=c)
    plot(a1['t'],a1['adc'],color=c)
    plot(a2['t'],a2['adc'],color=c)
    xlim(twindow[0],twindow[1])
    subplot(312)
    fs = 1/(a1['t'].iloc[1]-a1['t'].iloc[0])
    psd(a1['adc']-mean(a1['adc']),Fs=fs,NFFT=4096,color=c)
    psd(a2['adc']-mean(a2['adc']),Fs=fs,NFFT=4096,color=c)
    #psd(a0['adc']-mean(a0['adc']),Fs=fs,NFFT=4096,color='red')
    subplot(313)
    psd(a1['adc']-mean(a1['adc']),Fs=fs,NFFT=4096,color=c)
    psd(a2['adc']-mean(a2['adc']),Fs=fs,NFFT=4096,color=c)
    psd(a0['adc']-mean(a0['adc']),Fs=fs,NFFT=4096,color='red')
    xlim(0,300)
    #figure()
    #specgram(a1['adc'],Fs=fs,NFFT=1024)
    #colorbar()
    #figure()
    #specgram(a2['adc'],Fs=fs,NFFT=1024)
    #colorbar()

In [25]:
plotTestData0("testdata/coverRot_6")

In [42]:
plotTestData0("pulsetestdata/02_inputSwap")

In [74]:
#plotTestData0("pulsetestdata/04_rewired")
plotTestData("pulsetestdata/06_dgndE",tmin=0,twindow=(29,30))

In [49]:
plotTestData("testdata/noEl_10",'green')

In [81]:
plotTestData("testdata/noRotElCov_8",'red')
plotTestData("testdata/noRot_7",'blue')

In [16]:
(-(30.0201-30.0508))*11000*3+4

1017.0999999999838

In [24]:
1024./33000

0.03103030303030303

In [23]:
2*5500

11000

In [30]:
plotTestData("testdata/sdB3Delay_14","green")

In [92]:
plotTestData("testdata/fullWithEApplied")

In [29]:
plotTestData("testdata/backToNormal_34",tmin=0,twindow=(0,35))
#plotTestData("testdata/motorFar_22",'red')

In [7]:
10/(30.2009-30.0125)

53.07855626326923

In [26]:
plotTestData("testdata/sdtest_35",tmin=0,twindow=(0,35))

In [30]:
plotTestData("/run/media/brant/6262-3935/0003",tmin=0,twindow=(0,30))

KeyError: MemoryError()

In [71]:
a = dp.readData("pulsetestdata/06_dgndE")
specgram(a[2]['adc'],NFFT=1024*4,Fs=1/(a[2]['t'][2]-a[2]['t'][1]))

(array([[  1.43472722e+06,   1.57775707e+06,   1.39278080e+06, ...,
           1.40690755e+06,   1.40758532e+06,   1.40706585e+06],
        [  7.18215295e+05,   8.16758983e+05,   7.39427660e+05, ...,
           7.03862559e+05,   7.04472100e+05,   7.03850919e+05],
        [  7.96310516e+00,   4.61139841e+03,   2.97426954e+03, ...,
           6.53342839e-02,   2.73795429e-01,   3.69049021e-02],
        ..., 
        [  1.69934046e-04,   7.41146653e-04,   9.93417426e-04, ...,
           1.22555723e-05,   3.40405923e-05,   3.00079394e-05],
        [  7.21088440e-05,   2.42873457e-04,   9.78073092e-04, ...,
           8.93606657e-04,   1.53157207e-03,   6.06323774e-04],
        [  4.65977159e-04,   1.23488317e-03,   5.66855948e-04, ...,
           1.08715847e-03,   1.03196392e-03,   3.49425812e-04]]),
 array([  0.00000000e+00,   2.69144901e+00,   5.38289802e+00, ...,
          5.50670467e+03,   5.50939612e+03,   5.51208757e+03]),
 array([  0.18577354,   0.54570976,   0.90564599,   1.2655822

In [25]:
plot(a[2]['t'],a[2]['adc'])
plot(a[1]['t'],a[1]['adc'])